### ISSUE TITLE
Is there a way to set the hop time between the vocoder frames?

### ISSUE THREAD

**Issue by karanvivekbhargava** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#21]
I'm using the vocoder frames from a wav file. These frames are supposed to be fed into a time delayed lstm where the output is of the order of 30 fps. Currently I'm getting the vocoder frames at 200 frames per second. Any ideas for the same would be great.

**Comment by JeremyCCHsu** [comment]
You can set the `frame_period` arg in `dio` (see the example in `demo`). The default is 5 ms (lower is recommended), yielding 200 fps. You can increase it, but I would expect a certain degree of degradation because of the down-sampling. It'll probably be very severe; I would suggest that you try self-reconstruction (as in `demo/demo.py` before you feed it to an LSTM.

**Comment by karanvivekbhargava** [comment]
Thank you for the quick reply and your suggestions. This is really great work!
On a side note, I was wondering how you'd approach a problem where you need to feed the audio world frames into a lstm and the output is a representation of images (fps = 30). There is a problem here.
The input is at say 200 fps and the output is 30 fps. I haven't seen any lstm architectures for the same. However, a recent paper in CVPR claims that it has used a model like this.

I'm not really expecting a reply for this since it's a very niche position, however, you're a person who has worked in this domain and I'd love to hear any advice you have. Thank you for your time

**Comment by JeremyCCHsu** [comment]
I don't have a hands-on experience on audio-visual signals, so you might want to consult other researchers who do. 

First, if your the image/video representation is *unrelated to human speech* (e.g. musical instruments, objects sounds, etc), you might want to use STFT instead of a **vocoder** (e.g. WORLD/STRIGHT) because the latter distorts or even ignores speech-unrelated signals. (You can verify this by analyzing and then synthesizing a singing song with music.)

Second, you can adjust the frame rate to match the video's fps. At least two choices are available:
  1) set `frame_period=1000/30`.
  2) set `frame_period` to smaller values (say, `1000/240`), and then down-sample the output speech feature to 30 fps (8x in this case; using either standard DSP or a CNN).  

Make sure that the output is properly aligned because sometimes non-integer frame rate may give you additional frame(s) (either in WORLD or in STFT. Do whatever is needed to deal with it. Also note that some video coding could sometimes unexpectedly give you extra frames.

Hope you find it useful and wish you the best for your research.
