### ISSUE TITLE
While import pyworld, it encounters error

### ISSUE THREAD

**Issue by knaffe** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#9]
I install pyworld in Ubuntu 14.04, 64bit, python 3.4.3.
when I import pyworld, it encounters error.
>>> import pyworld 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/Python-Wrapper-for-World-Vocoder/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
ImportError: No module named 'pyworld.pyworld'

How to deal with it??????????

**Comment by JeremyCCHsu** [comment]
If you install pyworld using `pip install .`, then you can avoid this error simply by writing/running you code outside the `Python-Wrapper-for-World-Vocoder` folder. And in this case, I'm not sure if this is an error (it's caused by  `__init__.py`). If someone has a better answer to this, please tell us.

**Comment by pangwenfeng** [comment]
Thanks the suggestion from JeremyCCHs, it just fixes my problem.
